oa3_spec: openapi/generated/api_io_sign.yaml
name: opex_iobackend_api_io_sign
location: West Europe
timespan: 5m
evaluation_frequency: 10
evaluation_time_window: 30
event_occurrences: 4 # After 5*4=20 min
data_source: /subscriptions/ec285037-c673-4f58-b594-d7c480da4e8b/resourceGroups/io-p-itn-common-rg-01/providers/Microsoft.Network/applicationGateways/io-p-itn-agw-01
resource_type: app-gateway
action_groups:
  # TBD: add action group for io-sign errors
  - /subscriptions/EC285037-C673-4F58-B594-D7C480DA4E8B/resourceGroups/io-p-sign-integration-rg/providers/Microsoft.Insights/actiongroups/SlackFirmaConIoTech
overrides:
  hosts:
    - app-backend.io.italia.it
    - api-app.io.pagopa.it
  endpoints:
    /api/sign/v1/metadata:
      availability_threshold: 0.90
      response_time_threshold: 3
    /api/sign/v1/qtsp/clauses:
      availability_threshold: 0.90
      response_time_threshold: 3
    /api/sign/v1/qtsp/clauses/filled_document:
      availability_threshold: 0.90
      response_time_threshold: 3
    /api/sign/v1/signatures:
      availability_threshold: 0.90
      response_time_threshold: 3
    /api/sign/v1/signature-requests:
      availability_threshold: 0.90
      response_time_threshold: 3
    /api/sign/v1/signature-requests/{id}:
      availability_threshold: 0.90
      response_time_threshold: 3
