oa3_spec: api_backend.yaml
name: opex_api_backend
location: West Europe
timespan: 5m
data_source: /subscriptions/ec285037-c673-4f58-b594-d7c480da4e8b/resourceGroups/io-p-rg-external/providers/Microsoft.Network/applicationGateways/io-p-appgateway
action_groups:
  - /subscriptions/ec285037-c673-4f58-b594-d7c480da4e8b/resourceGroups/io-p-rg-common/providers/microsoft.insights/actionGroups/SlackPagoPA
  - /subscriptions/ec285037-c673-4f58-b594-d7c480da4e8b/resourceGroups/io-p-rg-common/providers/microsoft.insights/actionGroups/EmailPagoPA
overrides:
  hosts:
    - app-backend.io.italia.it
    - api-app.io.pagopa.it
  endpoints:
    /api/v1/payment-requests/{rptId}:
      response_time_threshold: 7
      availability_threshold: 0.25
