name: Opex Dashboard api_backend

on:
  push:
    branches: [features/opex]
    paths:
      - "api_*.yaml"
      - "openapi/**/*.yaml"
      - ".opex/**"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

permissions:
  id-token: write
  contents: read

jobs:
  test_opex_dashboards:
    uses: pagopa/dx/.github/workflows/opex-dashboard-deploy.yaml@chores/opex-workflow
    secrets: inherit
