oa3_spec: openapi/generated/api_fims_platform.yaml
name: opex_iobackend_api_fims_platform
location: West Europe
timespan: 5m
evaluation_frequency: 10
evaluation_time_window: 30
event_occurrences: 4 # After 5*4=20 min
data_source: /subscriptions/ec285037-c673-4f58-b594-d7c480da4e8b/resourceGroups/io-p-itn-common-rg-01/providers/Microsoft.Network/applicationGateways/io-p-itn-agw-01
action_groups:
  - /subscriptions/ec285037-c673-4f58-b594-d7c480da4e8b/resourceGroups/io-p-itn-msgs-rg-01/providers/Microsoft.Insights/actiongroups/io-p-com-error-ag-01
overrides:
  hosts:
    - app-backend.io.italia.it
    - api-app.io.pagopa.it
  endpoints:
    /api/fims/v1/accesses:
      response_time_threshold: 1
      availability_threshold: 0.90
    /api/fims/v1/export-requests:
      response_time_threshold: 1
      availability_threshold: 0.90
